{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import plotly\n",
    "import pandas as pd\n",
    "\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "from nltk.tokenize import word_tokenize\n",
    "\n",
    "from flask import Flask\n",
    "from flask import render_template, request, jsonify\n",
    "from plotly.graph_objs import Bar\n",
    "from sklearn.externals import joblib\n",
    "from sqlalchemy import create_engine\n",
    "\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "def tokenize(text):\n",
    "    tokens = word_tokenize(text)\n",
    "    lemmatizer = WordNetLemmatizer()\n",
    "\n",
    "    clean_tokens = []\n",
    "    for tok in tokens:\n",
    "        clean_tok = lemmatizer.lemmatize(tok).lower().strip()\n",
    "        clean_tokens.append(clean_tok)\n",
    "\n",
    "    return clean_tokens\n",
    "\n",
    "# load data\n",
    "engine = create_engine('sqlite:///../data/DisasterResponse.db')\n",
    "df = pd.read_sql_table('Messages', engine)\n",
    "\n",
    "# load model\n",
    "model = joblib.load(\"../models/classifier.pkl\")\n",
    "\n",
    "\n",
    "# index webpage displays cool visuals and receives user input text for model\n",
    "@app.route('/')\n",
    "@app.route('/index')\n",
    "\n",
    "def index():\n",
    "    \n",
    "    # extract data needed for visuals\n",
    "    # Calculate message count by genre and related status    \n",
    "    genre_related = df[df['related']==1].groupby('genre').count()['message']\n",
    "    genre_not_rel = df[df['related']==0].groupby('genre').count()['message']\n",
    "    genre_names = list(genre_related.index)\n",
    "    \n",
    "    # Calculate proportion of each category with label = 1\n",
    "    cat_props = df.drop(['id', 'message', 'original', 'genre'], axis = 1).sum()/len(df)\n",
    "    cat_props = cat_props.sort_values(ascending = False)\n",
    "    cat_names = list(cat_props.index)\n",
    "     \n",
    "\n",
    "    # create visuals\n",
    "    graphs = [\n",
    "        {\n",
    "            'data': [\n",
    "                Bar(\n",
    "                    x=genre_names,\n",
    "                    y=genre_related,\n",
    "                    name = 'Related'\n",
    "                ),\n",
    "                \n",
    "                Bar(\n",
    "                    x=genre_names,\n",
    "                    y=genre_not_rel,\n",
    "                    name = 'Not Related'\n",
    "                )\n",
    "            ],\n",
    "\n",
    "            'layout': {\n",
    "                'title': 'Distribution of Messages by Genre and Related Status',\n",
    "                'yaxis': {\n",
    "                    'title': \"Count\"\n",
    "                },\n",
    "                'xaxis': {\n",
    "                    'title': \"Genre\"\n",
    "                },\n",
    "                'barmode': 'group'\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            'data': [\n",
    "                Bar(\n",
    "                    x=cat_names,\n",
    "                    y=cat_props\n",
    "                )\n",
    "            ],\n",
    "\n",
    "            'layout': {\n",
    "                'title': 'Proportion of Messages by Category',\n",
    "                'yaxis': {\n",
    "                    'title': \"Proportion\"\n",
    "                },\n",
    "                'xaxis': {\n",
    "                    'title': \"Category\",\n",
    "                    'tickangle': -45\n",
    "                }\n",
    "            }\n",
    "        }\n",
    "    ]\n",
    "    \n",
    "    # encode plotly graphs in JSON\n",
    "    ids = [\"graph-{}\".format(i) for i, _ in enumerate(graphs)]\n",
    "    graphJSON = json.dumps(graphs, cls=plotly.utils.PlotlyJSONEncoder)\n",
    "    \n",
    "    # render web page with plotly graphs\n",
    "    return render_template('master.html', ids=ids, graphJSON=graphJSON)\n",
    "\n",
    "# web page that handles user query and displays model results\n",
    "@app.route('/go')\n",
    "def go():\n",
    "    # save user input in query\n",
    "    query = request.args.get('query', '') \n",
    "\n",
    "    # use model to predict classification for query\n",
    "    classification_labels = model.predict([query])[0]\n",
    "    classification_results = dict(zip(df.columns[4:], classification_labels))\n",
    "\n",
    "    # This will render the go.html Please see that file. \n",
    "    return render_template(\n",
    "        'go.html',\n",
    "        query=query,\n",
    "        classification_result=classification_results\n",
    "    )\n",
    "\n",
    "\n",
    "def main():\n",
    "    app.run(host='0.0.0.0', port=3001, debug=True)\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
